package org.eltech.ddm.miningcore;

public enum MiningErrorCode {
	INVALID_ARGUMENT,
	INVALID_DATA_TYPE,
	INVALID_OBJECT_TYPE,
	UNSUPPORTED,
	WRONG_IMPLEMENTATION,
	INVALID_INDEX,
	INVALID_INPUT_DATA,
	PARALLEL_EXECUTION_ERROR,
	NON_MERGEABLED_ELEMEN

}
